version: "3.8"

services:
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "7.4"
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: service:db
  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
  mail:
    image: mailhog/mailhog
    logging: 
      driver: 'none'
    network_mode: service:db

volumes:
  mariadb-data: